language: java
cache:
  directories:
    - $HOME/.m2

# visual tests
services:
  - xvfb

#download codacy jar
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

