language: java
cache:
  directories:
    - $HOME/.m2

# visual tests
services:
  - xvfb

#download codacy jar
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
  - mvn clean verify jacoco:report coveralls:report -Dmaven.javadoc.skip=true -B -q
  - ls target/site/
  - ls jcalendar/target/
  - ls jcalendar-testing-api/target/
  - ls jcalendar-demo/target/
  - ls jcalendar-demo-testing-api/target/
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r jcalendar/target/site/jacoco/jacoco.xml --partial
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r jcalendar-demo/target/site/jacoco/jacoco.xml --partial
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r jcalendar-demo-testing-api/target/site/jacoco/jacoco.xml --partial
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r jcalendar-testing-api/target/site/jacoco/jacoco.xml --partial
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r jcalendar/target/site/jacoco-aggregate/jacoco.xml --partial
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r jcalendar-demo/target/site/jacoco-aggregate/jacoco.xml --partial
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r jcalendar-demo-testing-api/target/site/jacoco-aggregate/jacoco.xml --partial
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r jcalendar-testing-api/target/site/jacoco-aggregate/jacoco.xml --partial
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar final
