# enviroment settings
    
image:
  - Visual Studio 2019
  - macOS

cache:
  - "./.m2/repository"
  - "./.m2/wrapper"
  - /maven
        
# install required tools (maven, secure-file, encrypted files)
install:
  - cmd: echo %JAVA_HOME%
  - cmd: echo %M2_HOME%

build_script:
  - mvn clean install -DskipTests -B -q

  # verify artifacts
test_script:
  - mvn verify -B -ntp

for:
-
    matrix:
      only:
      - image: macOS
      
    install:
        - brew install maven >/dev/null
        - export M2_HOME=/usr/local/Cellar/maven/3.6.3
        - export JAVA_HOME=$(/usr/libexec/java_home -v 1.8.0_232)
        - export PATH=$M2_HOME:$PATH
        - export PATH=$JAVA_HOME:$PATH
-
    matrix:
      only:
      - image: Visual Studio 2019


    environment:
        matrix:
            - JAVA_HOME: /Program Files/Java/jdk1.8.0