# enviroment settings
    
image:
  - Visual Studio 2019
  - macOS

environment:
 matrix:
    - JAVA_HOME: /Program Files/Java/jdk1.8.0

# install required tools (maven, secure-file, encrypted files)
install:
  - cmd: echo %JAVA_HOME%
  - cmd: echo %M2_HOME%

build_script:
  - mvn clean install -DskipTests -B

  # verify artifacts
test_script:
  - mvn verify -B

cache:
  - /maven

for:
-
    matrix:
      only:
      - image: macOS
      
    install:
        - echo $JAVA_HOME
        - brew install maven
        - export M2_HOME=/usr/local/Cellar/maven/3.6.3
        - echo $M2_HOME
        - export PATH=$M2_HOME:$PATH
        - echo $PATH
        - mvn -version