# enviroment settings
    
image:
  - Visual Studio 2019
  - macOS

cache:
  - "./.m2/repository"
  - "./.m2/wrapper"
        
# install required tools (maven, secure-file, encrypted files)
install:
  - cmd: echo %JAVA_HOME%
  - cmd: echo %M2_HOME%

build_script:
  - mvn clean install -DskipTests -B

  # verify artifacts
test_script:
  - mvn verify -B

for:
-
    matrix:
      only:
      - image: macOS
      
    install:
        - java -version
        - whereis javac
        - brew install maven
        - export M2_HOME=/usr/local/Cellar/maven/3.6.3
        - echo $M2_HOME
#        - export JAVA_HOME=`/usr/libexec/java_home -v 8 --exec javac -version`
        - export JAVA_HOME=`/Library/Java/JavaVirtualMachines/jdk1.8.0_232`
#        - /usr/lib/jvm/java-8-openjdk-amd64
        - export PATH=$M2_HOME:$PATH
        - export PATH=$JAVA_HOME:$PATH
        - echo $PATH
        - echo $JAVA_HOME
        - mvn -version
    environment:
        matrix:
            - JAVA_HOME: /usr
-
    matrix:
      only:
      - image: Visual Studio 2019

#    cache:
#      - /maven

    environment:
        matrix:
            - JAVA_HOME: /Program Files/Java/jdk1.8.0