/*
 * Copyright (C) 2019 Ruslan Lopez Carro.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package com.toedter.components;

import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Paint;

/**
 *
 * @author Ruslan Lopez Carro
 * @author Kai Toedter
 */
public class GradientPanel extends JPanel {

    private static final long serialVersionUID = -6385751027379193053L;

    private Color background;

    private Color controlColor;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Creates new form GradientPanel
     */
    public GradientPanel() {
        this(Color.BLUE);
    }

    public GradientPanel(Color background) {
        // Color controlColor = UIManager.getColor("control");
        // Color controlColor = new Color(252, 198, 82);
//        Color controlColor = new Color(165, 201, 215);
        this(background, new Color(99, 153, 255));
    }

    public GradientPanel(Color background, Color controlColor) {
        this.background = background;
        this.controlColor = controlColor;
        initComponents();
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);

        if (isOpaque()) {
            int width = getWidth();
            int height = getHeight();

            Graphics2D g2 = (Graphics2D) g;
            Paint oldPaint = g2.getPaint();
            g2.setPaint(new GradientPaint(0, 0, getBackground(), width, 0,
                    controlColor));
            g2.fillRect(0, 0, width, height);
            g2.setPaint(oldPaint);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(background);
        setLayout(new BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

}
